name: Docker Image CI

# Esto es el evento, cuando hacemos un push a esa rama
on:
  push:
    branches: [ "master" ]

# hace los siguientes trabajos

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Hacer checkout
      uses: actions/checkout@v4

    - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
        php-version: '8.2'

    - name: Instalar dependencias
      run: |
      composer install --no-dev

    - name: Ejecutamos tests
      run: vendor/bin/phpunit --testdox tests


  build:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - name: Hacer checkout
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}    
  
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USER }}/calculadora:latest
        




  #esto de abajo se puede eliminar
    - name: Construyendo la imagen
      run: docker build -t josedavidcases/calculadora:latest .
    - name: Subiendo imagen
      run: docker push ${{ secrets.DOCKER_user }}/calculadora:latest
    #- name: Build the Docker image
    #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)